/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package com.algo2.guicalc.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUM = 1;
  /** RegularExpression Id. */
  int OPEN = 2;
  /** RegularExpression Id. */
  int CLOSE = 3;
  /** RegularExpression Id. */
  int PLUSOP = 4;
  /** RegularExpression Id. */
  int MINUSOP = 5;
  /** RegularExpression Id. */
  int MULTIOP = 6;
  /** RegularExpression Id. */
  int DIVIDEOP = 7;
  /** RegularExpression Id. */
  int EQUALOP = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<NUM>",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
